on:
  push:
    branches:
      - main
jobs:
  call:
    uses: LaisLora/github-actions-templates/.github/workflows/template_python.yml@main
    with:
      environment: dev
      project: python_py
    secrets: inherit  
 
 
